ALTER TABLE IF EXISTS orders
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS stripe_refund_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS refund_amount DECIMAL(14, 2),
  ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS refund_currency VARCHAR(10),
  ADD COLUMN IF NOT EXISTS refund_reason VARCHAR(100);
