CREATE TABLE IF NOT EXISTS taxes (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  percentage DECIMAL(8, 4) NOT NULL DEFAULT 0 CHECK (percentage >= 0),
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_taxes_single_active
  ON taxes ((is_active))
  WHERE is_active = TRUE;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DECIMAL(14, 2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_id INTEGER REFERENCES taxes(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_name VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_percentage DECIMAL(8, 4) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(14, 2) DEFAULT 0;
