CREATE TABLE IF NOT EXISTS modifier_categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS modifier_subcategories (
  id SERIAL PRIMARY KEY,
  category_id INTEGER NOT NULL
    REFERENCES modifier_categories(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS modifier_groups
  ADD COLUMN IF NOT EXISTS category_id INTEGER
    REFERENCES modifier_categories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS subcategory_id INTEGER
    REFERENCES modifier_subcategories(id) ON DELETE SET NULL;
